### ISSUE TITLE
[Bug] Panic when im trying open a Powershell.lnk

### ISSUE THREAD

**Issue by McKpol** [lilopkins/lnk-rs#24]
ERROR:
```
C:/Users/McK/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Windows PowerShell\Windows PowerShell (x86).lnk
thread 'main' panicked at C:\Users\McK\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lnk-0.5.1\src\strings.rs:3:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[0501/111010.036:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
```

Example (Its still crash): 
```
match lnk::ShellLink::open("C:/Users/McK/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Windows PowerShell/Windows PowerShell (x86).lnk") {
    Ok(_) => println!("Works"),
    Err(e) => println!("{e}"),
  }
```

**Comment by iKineticate** [comment]
> ERROR:
> 
> ```
> C:/Users/McK/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Windows PowerShell\Windows PowerShell (x86).lnk
> thread 'main' panicked at C:\Users\McK\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lnk-0.5.1\src\strings.rs:3:34:
> called `Option::unwrap()` on a `None` value
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> [0501/111010.036:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
> ```
> 
> Example (Its still crash):
> 
> ```
> match lnk::ShellLink::open("C:/Users/McK/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Windows PowerShell/Windows PowerShell (x86).lnk") {
>     Ok(_) => println!("Works"),
>     Err(e) => println!("{e}"),
>   }
> ```

[The issue has been resolved previously, but the library hasn't been updated yet.](https://github.com/lilopkins/lnk-rs/commit/a202174f93e1d233b722f35dec827f892c89c66)

**Comment by GuoJikun** [comment]
me too.
